-- Kiểm tra cấu trúc bảng Cars
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Cars' 
AND TABLE_SCHEMA = 'dbo'
ORDER BY ORDINAL_POSITION;
